version: "3.1"

services:
  postgres:
    image: postgres:10.1
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    volumes:
      # - ./z-postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data

    ports:
      - 5432:5432
